### ISSUE TITLE
Please include a lib/ folder with the Java

### ISSUE THREAD

**Issue by mullachv** [brooklyn-omniheurists/evasion#2] opened 2015-10-31 07:34 UTC
Please include the dependent libraries so as to use App.java:
- glassfish tyrus version number and .jar file
- Jackson JSON parser version number and .jar file

**Comment by brooklyn-omniheurists** [comment] 2015-11-01 02:09
We'll use a bundled jar file, how does that sound? If possible, use [maven](https://maven.apache.org)!

**Comment by dkelmer** [comment] 2015-11-01 02:46
the maven build was supposedly successful:
[INFO] Building jar: /Users/dannakelmer/Documents/nyu/HPS/evasion/evasion/target/evasion-0.0.1-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 41.794s
[INFO] Finished at: Sat Oct 31 21:55:08 EDT 2015
[INFO] Final Memory: 12M/81M
[INFO] ------------------------------------------------------------------------

but 
$ java -cp target/evasion-0.0.1-SNAPSHOT.jar evasion.evasion.App
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/JsonProcessingException
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
    at java.lang.Class.privateGetMethodRecursive(Class.java:3040)
    at java.lang.Class.getMethod0(Class.java:3010)
    at java.lang.Class.getMethod(Class.java:1776)
    at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
    at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.JsonProcessingException
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 7 more

**Comment by brooklyn-omniheurists** [comment] 2015-11-01 03:34
I have just committed an updated version of the code. Please run below:

```
mvn clean install
```

then 

```
java -jar evasion-0.0.1-SNAPSHOT-jar-with-dependencies.jar
```

**Comment by mullachv** [comment] 2015-11-01 04:07
What version of Jackson JSON jar are you using? I am not able to deduce that from your maven pom.xml file. The rest of them appear to be retrievable from the web

**Comment by brooklyn-omniheurists** [comment] 2015-11-01 04:14
Looks like its `2.2.0`

**Closed as completed** 2015-11-04 01:30 UTC
